apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccountName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kete-runner.labels" . | nindent 4 }}
