// Package netrules generates the job's nftables ruleset (module README "Firewall"): only the
// proxy user may reach TCP 443 outbound (never a blocked range) and the configured resolvers on
// port 53; the kete user may reach only port A on loopback; the tool user only port B and its own
// loopback listeners on ports ≥ 1024; root only port R; everything else — Fly's private network
// and the metadata service included — is refused, for IPv4 and IPv6 alike. Refused, not silently
// dropped: a disallowed TCP connect gets a reset (ECONNREFUSED at once) and anything else an ICMP
// port-unreachable, so a misrouted client fails fast instead of hanging until its own timeout.
//
// Configuration v2 adds, for the proxy user only: the forbidden ranges refused before anything
// else, each internal range on exactly its ports, and a literal upstream proxy address on its port.
//
// Generate only prints text; `kete-egress nft` writes it to stdout and the entrypoint applies it
// with `nft -f -` as root. The output both installs and re-installs the table atomically.
package netrules

import (
	"fmt"
	"net/netip"
	"strconv"
	"strings"

	"github.com/kete-org/ketecode/packages/kete-egress/internal/blocked"
	"github.com/kete-org/ketecode/packages/kete-egress/internal/config"
)

// Table is the nftables table name (family inet).
const Table = "kete_egress"

// Priority is the output hook's priority: after conntrack (-200) and before any destination NAT
// (-100), so a rule sees the destination the process actually asked for.
const Priority = -155

// Generate returns the complete ruleset for cfg.
func Generate(cfg *config.Config) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	var v4, v6 []string
	for _, r := range cfg.Resolvers {
		if r.Addr().Is4() {
			v4 = append(v4, r.Addr().String())
		} else {
			v6 = append(v6, r.Addr().String())
		}
	}

	version := config.Version
	if cfg.Version == config.VersionV2 {
		version = config.VersionV2
	}
	w("# Generated by kete-egress nft (config v%d). Apply as root: kete-egress nft --config <file> | nft -f -", version)
	w("table inet %s", Table)
	w("delete table inet %s", Table)
	w("")
	w("table inet %s {", Table)
	w("\tset blocked_v4 {")
	w("\t\ttype ipv4_addr")
	w("\t\tflags interval")
	w("\t\telements = { %s }", join(blocked.V4))
	w("\t}")
	w("")
	w("\tset blocked_v6 {")
	w("\t\ttype ipv6_addr")
	w("\t\tflags interval")
	w("\t\telements = { %s }", join(blocked.V6))
	w("\t}")
	w("")
	if cfg.Version == config.VersionV2 {
		f4, f6 := split(blocked.Forbidden)
		w("\tset forbidden_v4 {")
		w("\t\ttype ipv4_addr")
		w("\t\tflags interval")
		w("\t\telements = { %s }", join(f4))
		w("\t}")
		w("")
		w("\tset forbidden_v6 {")
		w("\t\ttype ipv6_addr")
		w("\t\tflags interval")
		w("\t\telements = { %s }", join(f6))
		w("\t}")
		w("")
	}
	w("\tchain output {")
	w("\t\ttype filter hook output priority %d; policy drop;", Priority)
	w("\t\tct state established,related accept")
	w("\t\tct state invalid drop")
	w("\t\ticmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, mld2-listener-report } accept")
	w("\t\tmeta skuid %d jump proxy_out", cfg.UIDs.Proxy)
	w("\t\tmeta skuid %d jump kete_out", cfg.UIDs.Kete)
	w("\t\tmeta skuid %d jump tool_out", cfg.UIDs.Tool)
	w("\t\tmeta skuid 0 jump root_out")
	w("\t\tjump refuse")
	w("\t}")
	w("")
	w("\tchain refuse {")
	w("\t\tmeta l4proto tcp reject with tcp reset")
	w("\t\treject with icmpx port-unreachable")
	w("\t}")
	w("")
	w("\tchain proxy_out {")
	if len(v4) > 0 {
		w("\t\tip daddr { %s } meta l4proto { udp, tcp } th dport %d accept", strings.Join(v4, ", "), config.ResolverPort)
	}
	if len(v6) > 0 {
		w("\t\tip6 daddr { %s } meta l4proto { udp, tcp } th dport %d accept", strings.Join(v6, ", "), config.ResolverPort)
	}
	if cfg.Version == config.VersionV2 {
		// egress-config-v2.md "Behaviour": nothing forbidden, whatever an internal range says;
		// then each internal range on exactly its ports, and the upstream proxy's literal address
		// on its port (a proxy named by DNS must sit in an internal range or on 443).
		w("\t\tip daddr @forbidden_v4 jump refuse")
		w("\t\tip6 daddr @forbidden_v6 jump refuse")
		for _, r := range cfg.Internal {
			fam := "ip6"
			if r.Prefix.Addr().Is4() {
				fam = "ip"
			}
			w("\t\t%s daddr %s tcp dport { %s } accept", fam, r.Prefix, ports(r.Ports))
		}
		if up := cfg.Upstream; up != nil && up.Addr.IsValid() {
			w("\t\tip daddr %s tcp dport %d accept", up.Addr, up.Port)
		}
	}
	w("\t\tip daddr @blocked_v4 jump refuse")
	w("\t\tip6 daddr @blocked_v6 jump refuse")
	w("\t\ttcp dport 443 accept")
	w("\t}")
	w("")
	w("\tchain kete_out {")
	w("\t\tip daddr 127.0.0.1 tcp dport %d accept", cfg.Ports[config.PortKete])
	w("\t}")
	w("")
	w("\tchain tool_out {")
	w("\t\tip daddr 127.0.0.1 tcp dport %d accept", cfg.Ports[config.PortTool])
	w("\t\tip daddr 127.0.0.0/8 meta l4proto { tcp, udp } th dport >= 1024 accept")
	w("\t\tip6 daddr ::1 meta l4proto { tcp, udp } th dport >= 1024 accept")
	w("\t}")
	w("")
	w("\tchain root_out {")
	w("\t\tip daddr 127.0.0.1 tcp dport %d accept", cfg.Ports[config.PortRoot])
	w("\t}")
	w("")
	w("\tchain input {")
	w("\t\ttype filter hook input priority filter; policy drop;")
	w("\t\tct state established,related accept")
	w("\t\tct state invalid drop")
	w("\t\tiifname \"lo\" accept")
	w("\t\ticmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert, packet-too-big } accept")
	w("\t}")
	w("")
	w("\tchain forward {")
	w("\t\ttype filter hook forward priority filter; policy drop;")
	w("\t}")
	w("}")
	return b.String()
}

// split divides prefixes by family and drops any contained in another (nftables refuses
// overlapping elements in an interval set without auto-merge: ::1/128 lies in ::/96).
func split(ps []netip.Prefix) (v4, v6 []netip.Prefix) {
	for _, p := range ps {
		contained := false
		for _, o := range ps {
			if o != p && o.Bits() < p.Bits() && o.Contains(p.Addr()) {
				contained = true
			}
		}
		if contained {
			continue
		}
		if p.Addr().Is4() {
			v4 = append(v4, p)
		} else {
			v6 = append(v6, p)
		}
	}
	return v4, v6
}

func ports(ps []uint16) string {
	s := make([]string, len(ps))
	for i, p := range ps {
		s[i] = strconv.Itoa(int(p))
	}
	return strings.Join(s, ", ")
}

func join(ps []netip.Prefix) string {
	s := make([]string, len(ps))
	for i, p := range ps {
		s[i] = p.String()
	}
	return strings.Join(s, ", ")
}
