// The web UI inside the Kete Code VS Code extension. The extension frames the web UI in an iframe
// named "kete-vscode" (packages/kete-vscode/src/chat.ts); nothing here does anything elsewhere.
//
// - To the editor: when the user opens a changed file in the review, the extension opens its diff.
// - From the editor: the chat opens a new session for the VS Code workspace folder when it would show
//   Home, and "Send Selection/File to Chat" adds the file (and lines) to the prompt's context, the
//   same as the web UI's own "Add selection to context". Context sent before a prompt box exists
//   waits here until one mounts.
//
// Messages carry only workspace-relative paths and line numbers. Incoming ones are accepted only from
// the parent window (the extension's webview); the extension checks every path it receives.

import { useLocation } from "@solidjs/router"
import { createEffect, onCleanup, onMount } from "solid-js"
import { useComposerState } from "@/composer/persistence"
import { useGlobal } from "@/runtime/server/runtime"
import { ServerConnection } from "@/runtime/server/registry"
import { useTabs } from "@/shell/tabs/tabs"
import { openNotificationSession } from "@/shell/notifications/notification"
import { useTheme } from "@opencode/ui/theme/context"
import { KeteVSCodeTheme } from "./vscode-theme"
import "./tokens.css"
import { contextItemKey, type FileContextItem } from "@/composer/schema"
import {
  contextMessage,
  editorContextMessage,
  isNewSessionMessage,
  openSessionMessage,
  panelMessage,
  workspaceMessage,
  type ContextMessage,
} from "./vscode-messages"
import { updatePanelState } from "./panel-state"

// Per page load: context waiting for a prompt box, how many prompt boxes are listening, and the
// editor's current file/selection (shown as one context chip that follows the editor).
const pending: ContextMessage[] = []
const composers = { count: 0 }
const editor = { latest: undefined as ContextMessage | undefined }

function fileItem(message: ContextMessage): FileContextItem {
  return {
    type: "file",
    path: message.path,
    selection:
      message.startLine === undefined
        ? undefined
        : { startLine: message.startLine, startChar: 0, endLine: message.endLine ?? message.startLine, endChar: 0 },
  }
}

const frameName = "kete-vscode"

function embedded() {
  return typeof window !== "undefined" && window.name === frameName && window.parent !== window
}

/** Asks the extension to show `path` (relative to the workspace) as a diff in the editor. */
export function openDiff(path: string) {
  if (!embedded()) return
  // "*": the parent is the extension's webview, whose origin is generated by VS Code. The message
  // holds nothing secret, and the extension validates the path.
  window.parent.postMessage({ type: "kete.openDiff", path }, "*")
}

/** Dismisses one of the extension's notices; the panel hides it locally right away, and the
 *  extension's next `kete.panel` (after it persists the dismissal) is authoritative. */
export function dismissNotice(id: string) {
  if (!embedded()) return
  window.parent.postMessage({ type: "kete.dismissNotice", id }, "*")
}

export function dismissCliHint() {
  if (!embedded()) return
  window.parent.postMessage({ type: "kete.dismissCliHint" }, "*")
}

/** Mounted once in the app shell: opens the workspace and holds context until a prompt box exists. */
export function KeteVSCodeShell() {
  const global = useGlobal()
  const tabs = useTabs()
  const location = useLocation()
  const theme = useTheme()
  // Tokens set from VS Code's theme, so a later theme can clear the ones it doesn't set.
  const applied = new Set<string>()
  const applyTheme = (next: KeteVSCodeTheme.VSCodeTheme) => {
    theme.setColorScheme(KeteVSCodeTheme.mode(next))
    const values = KeteVSCodeTheme.tokens(next)
    const root = document.documentElement
    for (const token of applied) if (!(token in values)) root.style.removeProperty(token)
    applied.clear()
    for (const [token, value] of Object.entries(values)) {
      root.style.setProperty(token, value)
      applied.add(token)
    }
    root.dataset.keteHost = "vscode"
    // High-contrast themes: panel.css falls back its surfaces/borders/text to the VS Code-mapped
    // tokens above (tokens.css), since a fixed brand palette can't guarantee their contrast.
    if (next.kind.startsWith("high-contrast")) root.dataset.keteContrast = "high"
    else delete root.dataset.keteContrast
    window.parent.postMessage({ type: "kete.themeApplied", kind: next.kind, tokens: applied.size }, "*")
  }
  // The open session (from the route), for the extension's "Review Changes", diffs and session list.
  createEffect(() => {
    if (!embedded()) return
    const match = /\/session\/([^/]+)$/.exec(location.pathname)
    window.parent.postMessage({ type: "kete.session", sessionID: match ? decodeURIComponent(match[1]!) : null }, "*")
  })
  onMount(() => {
    if (!embedded()) return
    // `drafting`: a new chat still being opened; a session opened meanwhile waits for it, so the later
    // request wins.
    const workspace = {
      directory: undefined as string | undefined,
      opened: false,
      drafting: Promise.resolve() as Promise<unknown>,
    }
    // The server this page was paired with (the extension's own), by origin.
    const connection = () =>
      global.servers
        .list()
        .find((conn) => "http" in conn && URL.canParse(conn.http.url) && new URL(conn.http.url).origin === window.location.origin)
    const openWorkspace = (force = false) => {
      const conn = connection()
      if (!workspace.directory || !conn || (!force && (workspace.opened || location.pathname !== "/"))) return
      workspace.opened = true
      const context = global.ensureServerCtx(conn)
      context.projects.open(workspace.directory)
      context.projects.touch(workspace.directory)
      workspace.drafting = tabs.newDraft({ server: ServerConnection.key(conn), directory: workspace.directory }).catch(() => undefined)
    }
    const listener = (event: MessageEvent) => {
      if (event.source !== window.parent) return
      const vscodeTheme = KeteVSCodeTheme.themeMessage(event.data)
      if (vscodeTheme) return applyTheme(vscodeTheme)
      // The extension's notices, CLI hint and platform/default-mode for the empty state.
      const panel = panelMessage(event.data)
      if (panel) return updatePanelState({ host: "vscode", ...panel })
      // Remember the editor's file while no prompt box is open; the next one shows it.
      const current = editorContextMessage(event.data)
      if (current !== undefined) {
        if (composers.count === 0) editor.latest = current ?? undefined
        return
      }
      // A session picked in the editor's session list, or from a link: show it (and don't open a
      // new one for the workspace instead).
      const sessionID = openSessionMessage(event.data)
      if (sessionID) {
        const conn = connection()
        if (!conn) return
        workspace.opened = true
        // As the web UI's own notifications open a session: as a tab, then selected.
        void workspace.drafting.then(() => openNotificationSession(tabs, ServerConnection.key(conn), sessionID))
        return
      }
      // "New chat" from the editor: a new session for the workspace, wherever the chat is.
      if (isNewSessionMessage(event.data)) {
        openWorkspace(true)
        return
      }
      const directory = workspaceMessage(event.data)
      if (directory) {
        workspace.directory = directory
        openWorkspace()
        return
      }
      const context = contextMessage(event.data)
      if (!context || composers.count > 0) return
      pending.push(context)
      openWorkspace()
    }
    window.addEventListener("message", listener)
    onCleanup(() => window.removeEventListener("message", listener))
    window.parent.postMessage({ type: "kete.hello" }, "*")
  })
  return null
}

/** Mounted inside the composer providers of the session and new-session pages. */
export function KeteVSCodeBridge() {
  const prompt = useComposerState()

  const add = (message: ContextMessage) => {
    prompt.context.add(fileItem(message))
    window.parent.postMessage({ type: "kete.contextAdded", path: message.path }, "*")
  }
  // The editor chip: replaced as the editor moves; a sent message consumes it like any context.
  const follow = (next: ContextMessage | undefined) => {
    const previous = editor.latest
    editor.latest = next
    if (previous) prompt.context.remove(contextItemKey(fileItem(previous)))
    if (next) prompt.context.add(fileItem(next))
    window.parent.postMessage({ type: "kete.editorContextApplied", path: next?.path ?? null }, "*")
  }
  onMount(() => {
    if (!embedded()) return
    composers.count++
    pending.splice(0).forEach(add)
    // The editor's file arrived before this prompt box mounted (the shell kept it): show it, and tell
    // the extension it is applied, as `follow` does for later changes.
    if (editor.latest) {
      prompt.context.add(fileItem(editor.latest))
      window.parent.postMessage({ type: "kete.editorContextApplied", path: editor.latest.path }, "*")
    }
    const listener = (event: MessageEvent) => {
      if (event.source !== window.parent) return
      const current = editorContextMessage(event.data)
      if (current !== undefined) return follow(current ?? undefined)
      const message = contextMessage(event.data)
      if (message) add(message)
    }
    window.addEventListener("message", listener)
    onCleanup(() => {
      composers.count--
      window.removeEventListener("message", listener)
    })
  })
  return null
}
